### ISSUE TITLE
非垃圾 issue，只是没有找到其他方式联系你了

### ISSUE THREAD

**Issue by benjycui** [margox/margox.me#1]
你好，我是 [antd](http://ant.design/) 的 maintainer，同时也是 https://yuque.com/ 编辑器的开发者。

一个月前曾发邮件到你的邮箱 margox@foxmail.com ，至今没有收到回复，不知道是没兴趣还是没看到？

打扰了。

**Comment by margox** [comment]
啊，之前有看过邮件，不过当时过年家事太多就忘记了。我这边因为社保的原因暂时还不能离职（社保以及公积金交在长沙的，那边年底交了买房首付但是还没走到贷款流程，所以现在还不能断交），等落实好了会考虑一下，到时候联系你，你也可以先加我微信：Margox
